                             Assignment 2 Digit Recognition using KNN Classifier

In [334]:
#standard python imports to perform KNN

from sklearn import datasets
from sklearn.metrics import accuracy_score
from sklearn.model_selection import train_test_split
import matplotlib.pyplot as plt
import numpy as np
from sklearn.metrics import confusion_matrix
import math
import collections as col


In [335]:
# Loading digits data set

digits = datasets.load_digits()

n_samples = len(digits.images)

print(n_samples)

#size of each digit is 8*8 pixel.

print(digits.images.shape)


1797
(1797, 8, 8)


In [336]:
#Dividing data

data, target = digits.data , digits.target

print("arrays of digits will be\n",digits.data)

print("Target will be\n", digits.target)

data = digits.images.reshape((n_samples,-1))

#After falttening the image 

print("flattened data will be:\n",digits.data[0])

print("target will be:\n", digits.target[0])

print("flattend shape of entire data will be\n", data.shape)

arrays of digits will be
 [[ 0.  0.  5. ...  0.  0.  0.]
 [ 0.  0.  0. ... 10.  0.  0.]
 [ 0.  0.  0. ... 16.  9.  0.]
 ...
 [ 0.  0.  1. ...  6.  0.  0.]
 [ 0.  0.  2. ... 12.  0.  0.]
 [ 0.  0. 10. ... 12.  1.  0.]]
Target will be
 [0 1 2 ... 8 9 8]
flattened data will be:
 [ 0.  0.  5. 13.  9.  1.  0.  0.  0.  0. 13. 15. 10. 15.  5.  0.  0.  3.
 15.  2.  0. 11.  8.  0.  0.  4. 12.  0.  0.  8.  8.  0.  0.  5.  8.  0.
  0.  9.  8.  0.  0.  4. 11.  0.  1. 12.  7.  0.  0.  2. 14.  5. 10. 12.
  0.  0.  0.  0.  6. 13. 10.  0.  0.  0.]
target will be:
 0
flattend shape of entire data will be
 (1797, 64)


In [337]:
#splitting data into 50:50 ratio

X_train,X_test,y_train,y_test = train_test_split(data, target, test_size = 0.5,random_state = 42)

print(len(X_train), len(y_train), len(X_test))

print(X_train[1])
print(y_train[1])
print(X_test[1])
print(y_test[1])

898 898 899
[ 0.  0.  9. 16. 16.  7.  0.  0.  0.  2. 16. 11.  4. 15.  2.  0.  0.  4.
 16.  2.  2. 16.  6.  0.  0.  0. 13. 11. 13. 16. 10.  0.  0.  0.  1. 10.
 13. 16.  6.  0.  0.  0.  0.  0.  3. 16.  7.  0.  0.  0.  0.  2. 13. 14.
  1.  0.  0.  0. 11. 15. 15.  6.  0.  0.]
9
[ 0.  0. 11. 16.  8.  0.  0.  0.  0.  6. 16. 11. 13.  9.  0.  0.  0.  7.
 16.  0.  9. 16.  0.  0.  0.  2. 15. 12. 16. 16.  3.  0.  0.  0.  5.  7.
  7. 16.  4.  0.  0.  0.  0.  0.  5. 16.  5.  0.  0.  0.  3.  7. 16. 11.
  0.  0.  0.  0. 13. 16. 11.  1.  0.  0.]
9


In [338]:
def predict(X_train, y_train, X_test, k):
    distance = []
    targets  = []
    for i in range(len(X_train)):
        distance.append([np.sqrt(np.sum(np.square(X_test - X_train[i,:]))),i])
    distance = sorted(distance)
    for i in range(k):
        index = distance[i][1]
        targets.append(y_train[index])
    return targets
    

In [339]:
#a = predict(X_train, y_train, X_test,4)

In [340]:
def KNEAR(X_train, y_train, X_test, k):
    predictions = []
    for i in range(len(X_test)):
        predictions.append(predict(X_train, y_train, X_test[i,:], k))
    return np.asarray(predictions)
predictions = KNEAR(X_train, y_train, X_test, 50)
print(len(predictions))
print(len(y_test))

899
899


ValueError: Classification metrics can't handle a mix of multiclass and multiclass-multioutput targets

In [ ]:
def getAccuracy(y_test, predictions):
    correct = 0
    for x in range(len(y_test)):
        if y_test[x] is predictions[x]:
            corect +=1
    return (correct/float(len(y_test))) * 100.0
accuaracy = getAccuracy(y_test, predictions)
print(accuaracy)